site_name: Hydroglass
site_url: https://<your-username>.github.io/<your-repo>/
repo_url: https://github.com/<your-username>/<your-repo>
repo_name: <your-username>/<your-repo>
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 2
            show_signature: true
            separate_signature: true
            members_order: source
            inherited_members: false
            merge_init_into_class: true
            show_source: false
  - mkdocs-jupyter
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - API:
      - Lanczos: api/lanczos.md
      - Phonons: api/phonon.md